#!/bin/sh

set -e
missing=""

echo "Checking dependencies..."
gcc --version >/dev/null 2>&1 || (
  missing="gcc ${missing}"
  echo "MISSING: gcc"
)

if [ -n "$missing" ]
then
  echo
  echo "Please install $missing"
  exit 1
fi

echo
echo "Building whisper..."
make

echo
echo "Done!"
